"""syllabus entities: grade categories, scale bands, assignments, gradebook, office hours, class meetings, notes

Revision ID: 279e0c32799f
Revises: 9b5b0c9e800e
Create Date: 2026-07-30 18:38:49.050308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279e0c32799f'
down_revision: Union[str, None] = '9b5b0c9e800e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assignments_slug'), 'assignments', ['slug'], unique=True)
    op.create_table('class_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_meetings_course_id'), 'class_meetings', ['course_id'], unique=False)
    op.create_table('course_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_notes_course_id'), 'course_notes', ['course_id'], unique=False)
    op.create_table('grade_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('drop_lowest_n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_categories_course_id'), 'grade_categories', ['course_id'], unique=False)
    op.create_table('grade_scale_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=8), nullable=False),
    sa.Column('min_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_scale_bands_course_id'), 'grade_scale_bands', ['course_id'], unique=False)
    op.create_table('office_hour_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('zoom_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_hour_hosts_course_id'), 'office_hour_hosts', ['course_id'], unique=False)
    op.create_table('gradebook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('source_assignment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=True),
    sa.Column('points_possible', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['grade_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gradebook_entries_course_id'), 'gradebook_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_gradebook_entries_slug'), 'gradebook_entries', ['slug'], unique=True)
    op.create_table('office_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['office_hour_hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_hours_course_id'), 'office_hours', ['course_id'], unique=False)
    op.create_index(op.f('ix_office_hours_host_id'), 'office_hours', ['host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_office_hours_host_id'), table_name='office_hours')
    op.drop_index(op.f('ix_office_hours_course_id'), table_name='office_hours')
    op.drop_table('office_hours')
    op.drop_index(op.f('ix_gradebook_entries_slug'), table_name='gradebook_entries')
    op.drop_index(op.f('ix_gradebook_entries_course_id'), table_name='gradebook_entries')
    op.drop_table('gradebook_entries')
    op.drop_index(op.f('ix_office_hour_hosts_course_id'), table_name='office_hour_hosts')
    op.drop_table('office_hour_hosts')
    op.drop_index(op.f('ix_grade_scale_bands_course_id'), table_name='grade_scale_bands')
    op.drop_table('grade_scale_bands')
    op.drop_index(op.f('ix_grade_categories_course_id'), table_name='grade_categories')
    op.drop_table('grade_categories')
    op.drop_index(op.f('ix_course_notes_course_id'), table_name='course_notes')
    op.drop_table('course_notes')
    op.drop_index(op.f('ix_class_meetings_course_id'), table_name='class_meetings')
    op.drop_table('class_meetings')
    op.drop_index(op.f('ix_assignments_slug'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
