"""course.syllabus_committed_at

Revision ID: 32b25850f207
Revises: 279e0c32799f
Create Date: 2026-07-30 18:40:52.151997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b25850f207'
down_revision: Union[str, None] = '279e0c32799f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('syllabus_committed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'syllabus_committed_at')
    # ### end Alembic commands ###
